apiVersion: v1
kind: ReplicationController
metadata:
  name: jenkins-test
spec:
  replicas: 1
  selector:
    app: jenkins-test
  template:
    metadata:
      name: jenkins-test
      labels:
        app: jenkins-test
    spec:
      containers:
      - name: jenkins-test
        image: jenkins
        ports:
        - containerPort: 80
