apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: jenkins-test
  name: jenkins-test
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: jenkins-test
  type: NodePort
status:
  loadBalancer: {}
