apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    tier: frontend
  name: k8-rs
spec:
  ports:
  - port: 81
    protocol: TCP
    targetPort: 81
  selector:
    tier: frontend
  type: NodePort
status:
  loadBalancer: {}
