apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: nginx-dns
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    tier: nginx-dns
status:
  loadBalancer: {}
